import { osrs } from '../public/osrs.js';
import { esc, link, music, github } from '../public/view.js';

function paragraph(text) {
  // Content is text with optional Markdown links; arbitrary HTML never executes.
  return esc(text).replace(/\[([^\]]+)\]\((https:\/\/[^\s)]+)\)/g, (_, label, href) => link(href.replaceAll('&amp;', '&'), label));
}
export function page(site, favorites, activity, history = null) {
  const projectCard = (p, featured = false) => `<article${featured ? ' class="tomato-project"' : ''}><h3>${p.url ? link(p.url, esc(p.title)) : esc(p.title)}</h3><p>${paragraph(p.summary)}</p>${p.status && !p.url ? `<span class="project-status">${esc(p.status)}</span>` : ''}</article>`;
  const projects = site.projects.filter(p => p.title !== 'CanvasAPI');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#151318"><meta name="description" content="${esc(site.description)}"><meta property="og:title" content="${esc(site.title)}"><meta property="og:description" content="${esc(site.description)}"><meta property="og:type" content="website"><title>JWM — ${esc(site.title)}</title><link rel="preload" href="./assets/space-grotesk-bold.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="./assets/instrument-serif-italic.ttf" as="font" type="font/ttf" crossorigin><link rel="icon" href="./assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="./style.css"><script type="module" src="./app.js"></script></head>
<body><a class="skip-link" href="#about">Skip to about Jesse</a><div class="site" id="top">
<header class="site-header"><a class="site-name" href="#top" aria-label="JWM home">J<em>W</em>M</a><nav class="nav" aria-label="Main navigation"><a href="#workbench">making</a><a href="#music">listening</a><a href="#contact">say hello</a></nav></header>
<main><section class="intro" id="about" aria-labelledby="intro-title"><div class="intro-copy"><span class="location">${esc(site.name)} / ${esc(site.location)}</span><h1 id="intro-title" tabindex="-1">hi, I’m <em>${esc(site.firstName.charAt(0).toUpperCase() + site.firstName.slice(1))}.</em></h1><p class="intro-lead">I make games and small tools under <a href="#workbench">APT404</a>.</p></div><div class="thought" aria-hidden="true"><svg class="loop" viewBox="0 0 340 340" focusable="false"><g class="loop-lines" fill="none" stroke-width="1.5"><ellipse cx="170" cy="170" rx="124" ry="70" transform="rotate(-38 170 170)"/><ellipse cx="170" cy="170" rx="119" ry="73" transform="rotate(12 170 170)"/><ellipse cx="170" cy="170" rx="121" ry="71" transform="rotate(62 170 170)"/><ellipse cx="170" cy="170" rx="122" ry="69" transform="rotate(112 170 170)"/></g><circle class="loop-center" cx="170" cy="170" r="5"/></svg></div></section>
<section class="workbench" id="workbench" aria-labelledby="projects-title"><div class="section-heading"><h2 id="projects-title">things I’m making</h2><span>under APT404</span></div><div class="project-notes">${projects[0] ? projectCard(projects[0], true) : ''}<div class="other-projects">${projects.slice(1).map(p => projectCard(p)).join('')}</div></div></section>
<section class="music" id="music" aria-labelledby="music-title"><div class="section-heading"><h2 id="music-title">on repeat</h2><span>a few records along the way</span></div><div id="music-content">${music(activity.spotify, favorites, Date.now(), history)}</div></section>
<div class="footnotes"><aside class="game-note" id="game" aria-label="RuneScape account"><div id="osrs-content">${osrs(activity.wiseOldMan, activity.collectionLog, site.now.game, site.now.gameNote)}</div></aside><details class="background"><summary>the work &amp; school bit</summary><div>${site.about.map(p => `<p>${paragraph(p)}</p>`).join('')}<p>${esc(site.now.note)}</p></div></details></div>
${site.integrations.github ? `<details class="more-notes"><summary>GitHub</summary><section id="activity" class="section activity-section" aria-labelledby="activity-title"><h2 id="activity-title">lately on GitHub <span aria-hidden="true">↗</span></h2><div id="github-content">${github(activity.github, site.github)}</div></section></details>` : ''}<div class="contact" id="contact"><a href="mailto:${esc(site.email)}">email me</a>${link(`https://github.com/${site.github}`, 'github')}</div></main><footer><div class="footer-main"><span>© <span id="year">${new Date().getFullYear()}</span> ${esc(site.name)}</span><button id="loop-back" class="return-button">back to top</button></div></footer></div></body></html>`;
}
